<a href="https://colab.research.google.com/github/jeongjinjoo/Big-Data-practice/blob/main/7%ED%9A%8C%20%EA%B8%B0%EC%B6%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/happy2/happiness.csv',encoding='utf-8')
df.head()

,행복랭킹,나라명,점수,상대GDP,사회적지원,행복기대치,선택의 자유도,관대함,부패에 대한인식,년도
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019

In [18]:
#각 년도의 행복랭킹 10위를 차지한 나라의 행복점수 평균
# display(df)
result = df[df['행복랭킹'] == 10]['점수'].mean()
print(result)

7.259

In [29]:
# 각 년도의 행복랭킹 50위 이내의 나라
result = df[df['행복랭킹'] <= 50].sort_values('나라명')
# print(result)
result2 = result.groupby('나라명')['점수'].mean().to_frame()
print(result2)
#각각 행복점수 평균을 데이터프레임으로 표시

                          점수
나라명
Argentina             6.2370
Australia             7.2500
Austria               7.1925
Bahrain               6.1520
Belgium               6.9250
Belize                5.9560
Brazil                6.3595
Canada                7.3030
Chile                 6.4600
Colombia              6.1925
Costa Rica            7.1195
Cyprus                6.0460
Czech Republic        6.7815
Denmark               7.5775
Ecuador               6.0005
El Salvador           6.2100
Finland               7.7005
France                6.5405
Germany               6.9750
Guatemala             6.4090
Iceland               7.4945
Ireland               6.9990
Israel                6.9765
Italy                 6.1115
Kosovo                6.1000
Kuwait                6.0830
Lithuania             6.0505
Luxembourg            7.0000
Malaysia              6.3220
Malta                 6.6765
Mexico                6.5415
Netherlands           7.4645
New Zealand           7.3155
Nicaragua             6.1230
Norway                7.5740
Panama                6.3755
Poland                6.1525
Qatar                 6.3740
Romania               6.0700
Saudi Arabia          6.3730
Singapore             6.3025
Slovakia              6.1855
Slovenia              6.1180
Spain                 6.3320
Sweden                7.3285
Switzerland           7.4835
Taiwan                6.4435
Thailand              6.0720
Trinidad & Tobago     6.1920
United Arab Emirates  6.7995
United Kingdom        7.1220
United States         6.8890
Uruguay               6.3360
Uzbekistan            6.1350

In [39]:
# 2018년도 데이터들만 추출
df_1 = df[df['년도'] == 2018]
# print(df_1)
# 행복점수와 부패에 대한 인식에 대한 상관계수를 구하여라
result = df_1[['점수','부패에 대한인식']].corr().iloc[0,1]
print(result)

0.40529152271510027

In [51]:
#2018, 2019년도의 행복랭킹이 변화하지 않은 나라명의 수를 구하여라
result = len(df[['나라명','행복랭킹']]) - len(df[['나라명','행복랭킹']].drop_duplicates())
print(result)

15

In [56]:
# 2019년도 데이터만 가져오기
# 각변수간 상관계수를 구하고 내림차순으로 정렬후 상위 5개, 데이터프레임으로 출력

result = df[df['년도'] == 2019].corr().unstack().to_frame().reset_index().dropna()
print(result)

ValueError: could not convert string to float: 'Finland'

In [57]:
import pandas as pd
df= pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/consum/Tetuan%20City%20power%20consumption.csv')
df.head()

,DateTime,Temperature,Humidity,Wind Speed,general diffuse flows,diffuse flows,Zone 1 Power Consumption,Zone 2 Power Consumption,Zone 3 Power Consumption
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

In [65]:
#datetime컬럼을 통해 각 월별로 몇개의 데이터가 있는지
df['DateTime'] = pd.to_datetime(df['DateTime'])
result = df['DateTime'].dt.month.value_counts().sort_index().to_frame()
# print(result)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52416 entries, 0 to 52415
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   DateTime                   52416 non-null  datetime64[ns]
 1   Temperature                52416 non-null  float64
 2   Humidity                   52416 non-null  float64
 3   Wind Speed                 52416 non-null  float64
 4   general diffuse flows      52416 non-null  float64
 5   diffuse flows              52416 non-null  float64
 6   Zone 1 Power Consumption   52416 non-null  float64
 7   Zone 2  Power Consumption  52416 non-null  float64
 8   Zone 3  Power Consumption  52416 non-null  float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 3.6 MB
None

In [81]:
# 3월달 각 시간대별 온도의 평균 구하기
month = df[df['DateTime'].dt.month == 3]
result = month.groupby(month.DateTime.dt.hour)['Temperature'].mean().sort_values().values[0]
print(result)
# 가장 낮은 시간대의 온도

11.506612903225806

In [87]:
# Zone 1 Power Consumption 컬럼의 value값의 크기가 Zone 2 Power Consumption 컬럼의 value값의 크기보다 큰 데이터들의 Humidity의 평균을 구하여라
result = df[df['Zone 1 Power Consumption'] > df['Zone 2  Power Consumption']].Humidity.mean()
print(result)

68.23624448055052

 데이터 출처 : 자체 제작 데이터 설명 : 학생 15명의 국어, 수학,영어, 과학 시험 점수이다. 각 학생은 4과목 중 3과목을 선택해서 시험봤다.

In [88]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p1.csv')
df.head(5)

     학생    국어    수학    영어    과학
0  ID_0  63.0   NaN  79.0  84.0
1  ID_1  91.0  93.0   NaN  73.0
2  ID_2  59.0  55.0   NaN  56.0
3  ID_3  71.0  83.0  82.0   NaN
4  ID_4  62.0  72.0  56.0   NaN

국어,수학,영어,과학 과목 중 가장 많은 학생들이 응시한 시험을 선택하고 해당과목의 점수를 표준화 했을 때 가장 큰 표준화 점수를 구하여라

In [94]:
# 가장 많은 학생들이 응시한 시험
test = df.isnull().sum()
# print(test) # 국어
# 해당과목의 점수를 표준화했을때 가장 큰 표준화 점수
import numpy as np
# ddof() : 모표준편차
result = ((df['국어'] - df['국어'].mean())/ df['국어'].std(ddof = 0)).max()
print(result)

1.713855688712825

32개의 변수간 상관관계를 확인 했을 때, var_11 컬럼과 상관계수의 절댓값이 가장 큰 변수를 찾아 해당 변수의 평균값을 구하여라

In [119]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p2_.csv')
# df.head(5)
result = df.corr()
result1 = result['var_11'].abs().sort_values().index[-2]
result2 = df[result1].mean()
print(result2)

-0.06289356546077182

**var_6 컬럼의 1,3사분위수 각각 IQR의 1.5배 벗어난 이상치의 숫자를 구하라 **

In [120]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p3.csv')
df.head(5)

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,var_11,var_12
0,-0.401584,0.007198,-0.134910,-0.419514,-0.686331,-1.174550,-0.499150,-0.557510,0.357347,0.844209,0.082097,0.475098
1,1.064622,-0.531247,0.571185,-0.762243,-1.456043,0.355432,0.880010,0.523183,-0.141733,0.301472,0.840299,-0.045113
2,0.900195,-1.148496,-0.718437,-2.315266,-0.755505,0.630923,0.586027,0.086497,-0.381657,-1.602532,1.566340,-0.654105
3,1.199227,-0.114200,0.101536,-1.851971,-0.672844,0.796077,0.644246,-0.836296,-1.707074,0.376281,1.303967,1.228015
4,0.607393,1.675917,1.063759,-0.799493,-0.959568,-0.103007,-0.245984,-0.059492,0.293592,-0.517044,0.100772,0.403833

In [129]:
IQR_1 = df['var_6'].quantile(0.25)
IQR_3 = df['var_6'].quantile(0.75)
IQR = IQR_3 - IQR_1

min = IQR_1 - 1.5 * IQR
max = IQR_3 + 1.5 * IQR
# print(IQR_1)
# print(IQR_3)
print(df[(df['var_6'] < min) | (df['var_6'] > max)])

        var_1     var_2     var_3     var_4     var_5     var_6     var_7  \
61  -1.052026  2.671477 -0.063735  0.443091 -0.252952 -2.896629 -1.356372
80   2.601718 -0.689163  0.187056 -0.333682 -2.656683  2.704264  2.525497
94   0.945275 -1.588204  0.265805 -0.599865 -0.715023  2.824044  1.949872
148 -0.469255 -0.518196 -0.880794 -1.353235  0.107554 -2.727164 -0.949754
164  1.649083 -1.819321 -0.747122 -1.675070 -0.100709  2.620420  2.573300
282 -2.341044 -0.742030 -0.160838 -0.802164  1.180016 -2.511238 -2.128845
399  0.228232 -1.704387 -1.788963 -0.418815  0.570391  2.767266  1.329747
406  2.284573 -0.907189  1.668205 -0.340220 -2.328300  2.870425  2.622832

        var_8     var_9    var_10    var_11    var_12
61  -2.357715  0.639064  2.670374  1.449786  0.797494
80   0.963460 -0.383575 -0.839918 -0.440121 -0.844644
94  -0.040541  0.834281 -0.689715 -1.907044 -1.174152
148 -1.205864 -0.501184 -0.188367  1.197877  1.438212
164 -0.726533  0.111689  0.976327  0.070566 -1.065747
282 -2.112788  0.909893  0.566646 -0.128865  0.441990
399  1.215876 -2.031456 -0.063696  0.102048  0.748930
406  0.122462 -0.395515  0.137565 -1.989252 -0.532338

In [170]:
# 종속변수 :이용금액 , 평가지표 : rmse
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p2_train2.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p2_test2.csv')

# print(train.info())
# print(test.info()) # 이용금액이 종속변수

# 라벨인코딩
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

train['ID'] = le.fit_transform(train['ID'])
train['업종명'] = le.fit_transform(train['업종명'])
train['이용자구분'] = le.fit_transform(train['이용자구분'])
train['성별'] = le.fit_transform(train['성별'])

test['ID'] = le.fit_transform(test['ID'])
test['업종명'] = le.fit_transform(test['업종명'])
test['이용자구분'] = le.fit_transform(test['이용자구분'])
test['성별'] = le.fit_transform(test['성별'])

from sklearn.model_selection import train_test_split
x = train.drop(columns = ['ID','이용금액'])
y = train['이용금액']

X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size = 0.2,random_state = 42)

from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(random_state = 1)
rfr.fit(X_train, Y_train)
pred = rfr.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test, pred)

import numpy as np
rmse = np.sqrt(mse)
# print(rmse)

#최종 결과 예측
test_x = test.drop(columns = ['ID'])
pred2 = rfr.predict(test_x)

pd.DataFrame({'이용금액 : ' : pred2}).to_csv('008003.csv', index = False)
print(pd.read_csv('008003.csv'))

# # pred_test = rfr.predict()

           이용금액 :
0     7.291223e+09
1     4.686829e+07
2     2.391635e+06
3     4.460381e+06
4     5.224134e+05
...            ...
5015  3.821287e+08
5016  1.501010e+08
5017  5.360403e+09
5018  9.266131e+08
5019  8.667124e+08

[5020 rows x 1 columns]

In [166]:
# 종속변수 :이용금액 , 평가지표 : rmse
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p2_train2.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p2_test2.csv')

print(train.info())
print(test.info()) # 이용금액이 종속변수

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2245 entries, 0 to 2244
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      2245 non-null   object
 1   연월      2245 non-null   int64
 2   업종명     2245 non-null   object
 3   이용자구분   2245 non-null   object
 4   성별      2245 non-null   object
 5   이용자수    2245 non-null   int64
 6   이용건수    2245 non-null   int64
 7   이용금액    2245 non-null   int64
dtypes: int64(4), object(4)
memory usage: 140.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5020 non-null   object
 1   연월      5020 non-null   int64
 2   업종명     5020 non-null   object
 3   이용자구분   5020 non-null   object
 4   성별      5020 non-null   object
 5   이용자수    5020 non-null   int64
 6   이용건수    5020 non-null   int64
dtypes: int64(3), object(4)
memory usage: 274.7+ KB
None